FROM oven/bun:1
    
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    fonts-wqy-zenhei fonts-freefont-ttf 

WORKDIR /app
COPY . .
RUN bun install --frozen-lockfile

# Start
WORKDIR /app/packages/pptr
ENTRYPOINT ["bun", "run", "serve"]